### ISSUE TITLE
[InvalidArgumentException]   Class "" used for service "dzunke\slackbundle\command\botmessagingcommand" cannot be found.

### ISSUE THREAD

**Issue by RonanSauvage** [DZunke/SlackBundle#37]
Hello @DZunke,

Thx for your work & this component. 

I have been using this for several months without any problem. He is integrate in Symfony stack (v2.8 & more). Since yesterday in 2.4.0 I've a problem with service. 

When I wanna clear my cache, I've this Exception : 
 
```
[InvalidArgumentException]
  Class "" used for service "dzunke\slackbundle\command\botmessagingcommand" cannot be found.
```

My configuration is really minimalist. 

In my config.yml : 

```
# Monolog configuration             
monolog:
    handlers:
        # Slack logging
        slack:
            type: service
            id: log_slack

d_zunke_slack:
    token: "MyPrivateToken"
    verify_ssl: false
    identities:
        my_profile: 
            icon_url: 
            icon_emoji:
```
In my services.yml : 

```
log_slack:
        class: DZunke\SlackBundle\Monolog\Handler\SlackHandler
        # 400 = ERROR, see Monolog::Logger for the values of log levels
        arguments: ['@dz.slack.messaging', '%channel_slack%', "my_profile", 400]
```
Have you got the same behavior ? Do you need more informations ? 

Thx
